<?php

declare(strict_types=1);

namespace CoolMS\Dtmpl\Runtime;

use CoolMS\Dtmpl\AST\AssetNode;
use CoolMS\Dtmpl\AST\IncludeNode;
use CoolMS\Dtmpl\AST\Node;
use CoolMS\Dtmpl\AST\TemplateNode;
use CoolMS\Dtmpl\Exception\TemplateException;
use CoolMS\Dtmpl\TemplateLoaderInterface;

/**
 * Walks a compiled template and everything it includes, collecting the
 * `{css}` / `{js}` declarations into one deduplicated set.
 *
 * ⚠️ THIS IS A STATIC WALK AND THAT IS THE POINT. It follows every
 * {@see IncludeNode} it can see, including the ones inside `{if:}` branches
 * that this render will not take -- because "which branch runs" is a render
 * fact and the head is written before any of it happens. A page whose block
 * dispatch names fourteen partials therefore carries the styles of all
 * fourteen, once each, in a fixed order. That is the cost of having the
 * declaration live beside the markup instead of in a hand-maintained
 * stylesheet, and it is bounded: the set is the template's, not the data's,
 * so it does not grow with the number of blocks an author adds.
 *
 * Nothing here reads the render context, so the result depends only on the
 * template sources -- cacheable, and identical for every visitor.
 */
final class AssetGatherer
{
    /**
     * Include depth ceiling.
     *
     * The visited-path set already makes a cycle terminate; this bounds the
     * pathological non-cyclic case (a chain of distinct partials generated by
     * something) so a bad tree fails as a shallow gather rather than as a
     * stack overflow inside a page render.
     */
    private const int MAX_DEPTH = 32;

    /**
     * `$loader` is nullable for the same reason the Executor's is: an engine
     * used standalone has no include system, and a template that declares its
     * own `{css}` should still hand it over rather than fail.
     */
    public function __construct(
        private readonly ?TemplateLoaderInterface $loader,
        private readonly TemplateCompilerInterface $compiler,
    ) {
    }

    public function gather(TemplateNode $root, string $rootPath = ''): CollectedAssets
    {
        /** @var array<string, array{\CoolMS\Dtmpl\AST\AssetKind, string}> $fragments */
        $fragments = [];
        /** @var array<string, true> $visited */
        $visited = [];

        $this->walk($root, $rootPath, $fragments, $visited, 0);

        return CollectedAssets::fromFragments($fragments);
    }

    /**
     * @param array<string, array{\CoolMS\Dtmpl\AST\AssetKind, string}> $fragments
     * @param array<string, true>                                       $visited
     */
    private function walk(TemplateNode $template, string $path, array &$fragments, array &$visited, int $depth): void
    {
        foreach ($template->assets as $asset) {
            // First declaration wins its position; a later identical one is
            // dropped rather than moved, so the order a reader sees in the
            // head is the order the include tree declares.
            $fragments[$asset->key()] ??= [$asset->kind, $asset->source];
        }

        if (null === $this->loader || $depth >= self::MAX_DEPTH) {
            return;
        }

        foreach ($this->includesIn($template->children) as $include) {
            $resolved = $this->loader->resolve($include->templatePath, $path);
            if (isset($visited[$resolved])) {
                continue;
            }
            $visited[$resolved] = true;

            try {
                $source = $this->loader->load($include->templatePath, $path);
            } catch (TemplateException) {
                // ⚠️ A missing partial is NOT reported here. This walk is a
                // side pass whose only job is to collect declarations; the
                // render that follows loads the same path through the same
                // loader and raises the real error, with the real include
                // stack. Failing first, from here, would replace that message
                // with a worse one from a place the author did not write.
                continue;
            }

            $this->walk($this->compiler->compile($source), $resolved, $fragments, $visited, $depth + 1);
        }
    }

    /**
     * Every {@see IncludeNode} reachable from `$nodes`, in document order.
     *
     * ⚠️ Reflective rather than a match over node types, deliberately. A body
     * -- a loop's, a conditional's two branches, a fill's, a slot's default --
     * is just a public array of {@see Node} on the node that owns it, and the
     * one thing this walk must never do is quietly stop seeing a construct
     * because a node type was added and this list was not updated. A partial
     * whose styles silently stop being gathered renders unstyled in a way that
     * looks deliberate, which is the exact failure mode this whole mechanism
     * exists to remove.
     *
     * ⚠️ `mixed[]`, not `Node[]`: the recursion feeds this every public ARRAY
     * property it finds -- an IncludeNode's literal `$params`, a loop's
     * modifiers -- so the non-Node guard below is doing real work rather than
     * defending against an impossible type.
     *
     * @param mixed[] $nodes
     *
     * @return list<IncludeNode>
     */
    private function includesIn(array $nodes): array
    {
        $found = [];
        foreach ($nodes as $node) {
            if (!$node instanceof Node) {
                continue;
            }
            if ($node instanceof IncludeNode) {
                $found[] = $node;
            }
            if ($node instanceof AssetNode) {
                continue;
            }
            foreach (get_object_vars($node) as $value) {
                if ($value instanceof Node) {
                    $found = [...$found, ...$this->includesIn([$value])];
                } elseif (is_array($value)) {
                    $found = [...$found, ...$this->includesIn($value)];
                }
            }
        }

        return $found;
    }
}
